<a href="https://colab.research.google.com/github/tanpharamut/KKU_data_mining/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### numpy array

In [ ]:
np1 = np.array([[1,3,5],[2,4,6]])
np1

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
np2 = np.array([[1,2],[3,5],[2,0],[4,5]])
np2

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
np2.T

array([[1, 3, 2, 4],
       [2, 5, 0, 5]])

In [ ]:
np2[0,:]

array([1, 2])

## HW6 
สร้าง distance metrix (Euclidean) ของ np2
โดยสร้าง Function สำหรับคำนวณ Euclidean Distance
def Euclidean(data1,data2):
    #process
    return dist 

In [ ]:
def Manhattan(data1,data2):
    distX = abs(data1[0]-data2[0])
    distY = abs(data1[1]-data2[1])
    return distX+distY

In [ ]:
Manhattan(np2[0,:],np2[1,:])

5

In [ ]:
dist_mat = np.zeros((4,4))
dist_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
    for j in range(4):
        dist_mat[i,j] = Manhattan(np2[i,:],np2[j,:])
dist_mat        

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

In [ ]:
np2.shape

(4, 2)

In [ ]:
import math

In [ ]:
def Euclidean(data1,data2):
    distX = pow(abs(data1[0]-data2[0]),2)
    distY = pow(abs(data1[1]-data2[1]),2)
    return math.sqrt(distX+distY)

In [ ]:
dist_math1 = np.zeros((4,4))
dist_math1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
    for j in range(4):
        dist_math1[i,j] = Euclidean(np2[i,:],np2[j,:])
dist_math1

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

###Distance of nominal or categorical feature


### (eatra) Python data structure (Dictionary)

ใช้วงเล็บปีกกา

In [1]:
d_A = {'a':1,2:3,3:5,'cat':6}

In [2]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [3]:
d_A['cat']

6

เพิ่มค่า

In [5]:
d_A['dog'] = [1,2,3,4,5]

In [6]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [7]:
import pandas as pd

In [10]:
data_dict = {'color':['red','red','green'], #color = {'red','green','blue'}
             'status':['single','married','single']} #status = {'single','married','single'}
data_dict                   

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [11]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

###Categorical featore distance method#1

เรียกค่าเเต่ละ datapoint มา ตัวอย่าง เรียกตัวที่ 0

In [14]:
list(data_pd.iloc[0,:])

['red', 'single']

In [20]:
list(data_pd.iloc[1,:])

['red', 'married']

range เพิ่อเป็นกว้าง featore 

In [24]:
def math1_dist(data1,data2):
    N = 0
    print(f'data1 is {data1} and data2 is {data2}')
    for i in range(len(data1)):
        print(f'feature1 of data1 is {data1[i]} , feature1 of data2 is {data2[i]}')
        if data1[i] != data2[i]: # ดูที่ไม่เท่ากัน
            N = N+1
            print(f' {data1[i]} is not eual {data2[i]} : update ({N})')
        else:
            print(f' {data1[i]} is eual {data2[i]}')    
    return N/len(data1)        

In [26]:
math1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is ['red', 'single'] and data2 is ['red', 'married']
feature1 of data1 is red , feature1 of data2 is red
 red is eual red
feature1 of data1 is single , feature1 of data2 is married
 single is not eual married : update (1)


0.5

### HW7 calculate distance matrix of data_pd using mrth_dist()

###Categorical feature distance method#2

In [36]:
data_pd_binary = pd.get_dummies(data_pd)
data_pd_binary

color_green  color_red  status_married  status_single
0            0          1               0              1
1            0          1               1              0
2            1          0               0              1

In [42]:
def binary_sym_dist(data1,data2):
    rs = 0
    q = 0
    
    t = 0
    for i in range(len(data1)):
        if data1[i] == data2[i]:
            if data1[i] == 1:
                q = q + 1
            else:
                t = t + 1
        if data1[i] != data2[i]:
            rs = rs + 1

    return (rs)/(q+rs+t)            

In [43]:
binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

0.5

### HW8 calculate distance matrix of data_pd_binary using binary_sym_dist()